apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-service-deployment
  labels:
    app: activemq-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq-service
  template:
    metadata:
      labels:
        app: activemq-service
    spec:
      containers:
      - name: activemq-service
        image: systeamorg/activemq-service
        imagePullPolicy: Never
        ports:
        - containerPort: 61613
        - containerPort: 61616
        - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  labels:
    app: activemq-service
spec:
  ports:
  - port: 61616
    targetPort: 61616
    protocol: TCP
    name: tcp
    nodePort: 30011
  - port: 61613
    targetPort: 61613
    protocol: TCP
    name: stomp
    nodePort: 30012
  - port: 8161
    targetPort: 8161
    protocol: TCP
    name: console
    nodePort: 30013
  type: NodePort
  selector:
    app: activemq-service
